### PR TITLE
feat: add support for GladiusEx frames

### PR DESCRIPTION
**Pull request by ManuelHaag**

### CODE REVIEW

**Comment by vendethiel** [comment]
Neat. Thanks.

**Comment by jordonwow** [comment]
No problem, sorry about that.

**Comment by vendethiel** [comment]
Thank you for your quick response!

**Comment by parsimonious** [comment]
I think I may be one of those people who this was useful to. I opened #812 , I'm not 100% sure as my issue covers more than just GladiusEx, but I suspect this is also something I was using. Is it possible to reintroduce this, but perhaps make it opt-in? I understand vendethiel wants to avoid getting spammed with that issue, but I can't actually find a work-around within another addon at the moment.

**Pull request merged**
