### PR TITLE
Spell updates

### PR DESCRIPTION
**Pull request by domzae**
A number of old/unused id's removed, some new spells added
#185 included

### CODE REVIEW

**Comment by OperationXen** [comment]
I'm not sure that the base bigdebuffs is being actively maintained, last update November of last year.

**Comment by domzae** [comment]
Yeah, I assume Jordon isn't playing at the moment, but regardless he usually updates the addon if something breaks, so no harm in a simple pull request for next time he's here :)

**Comment by OperationXen** [comment]
I wonder if he'd be open to other devs coming on board with the project as maintainers

**Comment by Kennah229** [comment]
parent ID of alter time and touch of karma are wrong. and intervene spell ID also wrong, correct ID is 147833

**Pull request merged**
